site_name: Guides
site_author: "46620"
site_description: Random Guides for all
site_url: https://guides.46620.moe/
theme:
  name: material
  palette:
    scheme: slate
nav:
    - Main: 'index.md'
    - About: 'about.md'
    - Server:
        - Plex:
            - 'Installation': 'server/plex/install.md'
            - 'Anime Metadata': 'server/plex/metadata_anime.md'
            - 'Tautulli': 'server/plex/tautulli.md'
            - 'Tautulli Scripting': 'server/plex/tautulli_scripting.md'
    - PC:
        - Linux:
            - 'Single GPU passthrough': 'machine/linux/1gpu_pass.md'


markdown_extensions:
    - admonition
    - pymdownx.details
    - fontawesome_markdown
    - pymdownx.highlight
    - pymdownx.superfences