site_name: Guides
site_author: "46620"
site_description: Random Guides for all
site_url: https://guides.46620.moe/
theme:
  name: material
  palette:
    scheme: slate
nav:
    - Main: 'index.md'
    - About: 'about.md'
    - Server:
        - Plex:
            - 'Installation': 'server/plex/install.md'
            - 'Anime Metadata': 'server/plex/metadata_anime.md'
            - 'Tautulli': 'server/plex/tautulli.md'
            - 'Tautulli Scripting': 'server/plex/tautulli_scripting.md'
        - Jellyfin:
            - 'Installation': 'server/jellyfin/install.md'
            - 'Migrating from Plex': 'server/jellyfin/migrate.md'
            - 'Setting up IPTV and an EPG': 'server/jellyfin/iptv.md'
        - Games:
            - 'Project Zomboid': 'server/games/zomboid.md'
    - PC:
        - Linux:
            - Migrating from Windows to Linux:
                - 'Leaving Windows': 'machine/linux/migration/why.md'
                - 'Downsides': 'machine/linux/migration/downsides.md'
                - 'Prep': 'machine/linux/migration/prep.md'
                - 'Post Install': 'machine/linux/migration/post.md'
            - GPU Passthrough:
                - 'Requirements': 'machine/linux/gpu_passthrough/setup.md'
                - 'Single GPU passthrough': 'machine/linux/gpu_passthrough/1gpu_pass.md'
                - 'Not Single GPU passthrough': 'machine/linux/gpu_passthrough/2gpu_pass.md'
                - 'Masking the VM': 'machine/linux/gpu_passthrough/hide.md'


markdown_extensions:
    - admonition
    - pymdownx.details
    - fontawesome_markdown
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.tabbed:
        alternate_style: true 